### ISSUE TITLE
'BindingEvent' object has no attribute 'ipc_data'

### ISSUE THREAD

**Issue by bccoutinho** [windwp/i3-master-slave#2]
I tried this but got the error 

  File "i3_master_layout.py", line 520, in on_binding
    command = event.ipc_data["binding"]["command"].strip()
AttributeError: 'BindingEvent' object has no attribute 'ipc_data'

**Comment by windwp** [comment]
Are you using sway? what version of i3?

**Comment by tott** [comment]
Hi @windwp, 
I'd love to use your script but run into the same

```python3 i3_master_layout.py
'BindingEvent' object has no attribute 'ipc_data'
Traceback (most recent call last):
  File "i3_master_layout.py", line 680, in <module>
    main()
  File "i3_master_layout.py", line 645, in main
    i3.main()
  File "/usr/local/lib/python3.7/dist-packages/i3ipc/connection.py", line 518, in main
    raise loop_exception
  File "/usr/local/lib/python3.7/dist-packages/i3ipc/connection.py", line 497, in main
    while not self._event_socket_poll():
  File "/usr/local/lib/python3.7/dist-packages/i3ipc/connection.py", line 477, in _event_socket_poll
    raise e
  File "/usr/local/lib/python3.7/dist-packages/i3ipc/connection.py", line 474, in _event_socket_poll
    self._pubsub.emit(event_name, event)
  File "/usr/local/lib/python3.7/dist-packages/i3ipc/_private/pubsub.py", line 28, in emit
    s['handler'](self.conn, data)
  File "i3_master_layout.py", line 611, in on_binding
    handler.on_binding(event)
  File "i3_master_layout.py", line 543, in on_binding
    command = event.ipc_data["binding"]["command"].strip()
AttributeError: 'BindingEvent' object has no attribute 'ipc_data'
```

I'm using airbender i3-gaps (4791b22) i3 4.19-54-g4791b221

**Comment by windwp** [comment]
i use
 i3 i3 version 4.19 (2020-11-15) 
python 3.8.5 
i3ipc                   2.2.1

i think your issue come from i3ipc

**Comment by tott** [comment]
This looks like the same version I use 

```
>pip3 show i3ipc
Name: i3ipc
Version: 2.1.1
```

**Comment by windwp** [comment]
no 2.2.1 not 2.1.1

**Comment by tott** [comment]
:facepalm: that was it. just compiled 2.2.1 and things work fine. Thanks so much for entertaining my stupidity :)
